version: '3.3'

services: 
    postgresql:
        image: postgres:12
        #restart: always
        env_file:
            - ./postgresql/.env.dev
        volumes: 
            - postgres-data:/var/lib/postgresql/data
            - postgres-run:/var/run/postgresql
    cubicerp:
        image: c4a3d7d5aabe
        #restart: always
        depends_on:
            - postgresql
        command: python3 /home/cubicerp/ecbc/cubicerp/cubicerp-server -c /home/cubicerp/ecbc/config/cubicerp.conf
        volumes: 
            #- odoo-data:/var/lib/odoo/
            #- ./odoo/extra-addons/:/mnt/extra-addons/
            #- ./odoo/odoo.conf:/etc/odoo/odoo.conf
            - postgres-run:/var/run/postgresql
            - cubicerp-data:/home/cubicerp/ecbc/data
            - cubicerp-conf:/home/cubicerp/ecbc/config
        ports:
            - 8069:8069
        #env_file:
        #    - ./odoo/.env.dev
    #nginx:
        #build: ./nginx
        #restart: always
        #ports:
        #    - 80:80
        #    - 443:443
        #volumes:
        #    - ./nginx/ssl/:/etc/ssl/nginx/
        #    - ./nginx/sites-enabled/:/etc/nginx/conf.d/
        #links:
        #    - odoo
        #depends_on:
        #    - odoo
volumes: 
    postgres-run:
    postgres-data:
    cubicerp-data:
    cubicerp-conf:
